import "./globals.css";
import { Poppins } from "next/font/google";
import ContextProvider from "./context/GlobalContext";
import Header from "./components/Header";

const poppins = Poppins(
  {
    weight: ['400', '600'],
    subsets: ['latin'],
  }
)

export const metadata = {
  title: "BaxarCoder",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <ContextProvider>
          <Header />
          <main className="container">{children}</main>
        </ContextProvider>
      </body>
    </html>
  );
}
